import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useState } from 'react'

export default function Home() {
    const router = useRouter()
    const [menu, setMenu] = useState(false)
    const [arr, setArr] = useState([
        "square",
        "circle",
        "oval",
        "trapezoid",
        "rectangle",
        "parallelogram"
    ])
    const move = () => {
        let arr1 = arr[0]
        let arr2 = arr;
        let arr3 = [];
        for(let key in arr2) {
            let row = arr2[key];
            if(key != 0) {
                arr3.push(row)
            }
        }
        arr3.push(arr1);
        setArr(arr3)
        // console.log(arr)

    }

    console.log(arr)

    return ( 
    <div className = { styles.container }>
        <Head >
        <title> test </title>  
        < meta name = "description" content = "Generated by create next app"/>
        < link rel = "icon" href = "/favicon.ico" />
        </Head>



        <div className="container">
            <h1>
                {router.locale==='th' ? 'การจัดการหน้าเว็บ' :'style layout'}
            </h1>

            <div className="btn-lang">
                <button id='button-lang' href="" onClick={() => setMenu(menu === true ? false:true)}>TH</button>
                {menu === true &&
                <ul>
                    <li>
                        <Link href={"/"} locale="th">TH</Link>
                        </li>
                    <li>
                        <Link href={"/"} locale="en">EN</Link>
                        </li>
                </ul>
                }
            </div>

            <div className="d-flex">
                <button href="" id='one'>
                <div className="box">
                    <div id="triangle-left" onClick={() => move()}></div>
                    
                    <div className="txt">{router.locale==='th' ? 'เลือกรูปแบบ' :'Move Shape'}</div>
                </div>
                </button>
                
                <div className="box-pd">
                <button href="" id='two'>
                    <div className="box">
                        <div id="triangle-down"></div>
                    </div>
                </button>
                <button href="" id='three'>
                    <div className="box">
                        <div id="triangle-up"></div>
                    </div>
                </button>
                <div className="txt-c">เปลี่ยนตำแหน่ง</div>
                <div className="txt">{router.locale==='th' ? 'เปลี่ยนตำแหน่ง' :'Move Position'}</div>
                </div>

                <button href="" id='four'>
                <div className="box">
                <div id="triangle-right"></div>
                <div className="txt">{router.locale==='th' ? 'เลือกรูปแบบ' :'Move Shape'}</div>
                </div>
                </button>
            </div>

            <div className="line"></div>

            <div className="d-flex-r">
                {
                    arr.slice(0,3).map((item,i) => {
                        return(
                            <a href="" className='a-button' key={i}>
                            <div className="box">
                                <div id={item}></div>
                            </div>
                            </a>
                        )
                    })
                }


                {/* <a href="" className='a-button'>
                <div className="box">
                    <div id="square"></div>
                </div>
                </a>
                <a href="" className='a-button'>
                <div className="box">
                <div id="circle"></div>
                </div>
                </a>
                <a href="" className='a-button'>
                <div className="box">
                <div id="oval"></div>
                </div>
                </a> */}
            </div>

            <div className="d-flex-l">
                {/* <a href="" className='a-button'>
                <div className="box">
                    <div id="trapezoid"></div>
                </div>
                </a>
                <a href="" className='a-button'>
                <div className="box">
                <div id="rectangle"></div>
                </div>
                </a>
                <a href="" className='a-button'>
                <div className="box">
                <div id="parallelogram"></div>
                </div>
                </a> */}

                {
                    arr.slice(3).map((item,i) => {
                        return(
                            <a href="" className='a-button' key={i}>
                            <div className="box">
                                <div id={item}></div>
                            </div>
                            </a>
                        )
                    })
                }
            </div>



        </div>

        </div>
    )
}